import pandas as pd
import faiss
from sentence_transformers import SentenceTransformer
import anthropic
import streamlit as st
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

@st.cache_resource
def load_resources():
    embedder = SentenceTransformer('all-MiniLM-L6-v2')
    index = faiss.read_index(os.path.join(BASE_DIR, 'data', 'injury_index.faiss'))
    corpus = pd.read_csv(os.path.join(BASE_DIR, 'data', 'osha_corpus.csv'))
    return embedder, index, corpus

embedder, index, corpus = load_resources()

def retrieve(query, k=5):
    query = query.lower()

    query_embedding = embedder.encode([query]).astype('float32')

    distances, indices = index.search(query_embedding, k)

    results = []
    for dist, idx in zip(distances[0], indices[0]):
        row = corpus.iloc[idx]
        results.append({
            'text': row['Abstract Text'],
            'injury_type': row['Event type'],
            'distance': float(dist)
        })
    
    return results

def rag_query(query, results):
    # Retreive the top 5 results

    context = '\n\n'.join([
        f"Injury Type: {r['injury_type']}\nText: {r['text']}"
        for r in results
    ])

    prompt = f"""
    You are an occupational health analyst. 
    Use only the workplace injury records below to answer the question. 
    If the records don't contain enough information, say you are unsure.
    
    INJURY RECORDS:
    {context}

    QUESTION: 
    {query}"""

    client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
    
    response = client.messages.create(
        model='claude-sonnet-4-5',
        max_tokens=512,
        messages=[{'role': 'user', 'content': prompt}]
    )

    return response.content[0].text

st.set_page_config(page_title='Injury Intelligence', page_icon='🦺', layout='wide')

col1, col2 = st.columns([2, 1])
with col1:
    st.title('OSHA Injury Q&A')
    st.markdown("""
    **How it works**: your query is embedded using the `all-MiniLM-L6-v2` sentence transformer 
    model, and the top 5 most similar injury narratives are retrieved from a FAISS vector index. 
    These records are passed to Claude as context, which responds as an occupational health analyst 
    grounded in the retrieved data.

    **Pipeline**: a text classification model was built using TF-IDF + Logistic Regression 
    as a baseline, then compared against a fine-tuned DistilBERT model. 
    A FAISS vector index was constructed from narrative embeddings generated by the 
    `all-MiniLM-L6-v2` sentence transformer model.

    **Data**: sourced from [Kaggle](https://www.kaggle.com/datasets/ruqaiyaship/osha-accident-and-injury-data-1517), 
    this dataset contains 4,427 OSHA severe injury report abstracts from 2015–2017, including both structured fields 
    degree of injury, body parts affected) and free-text narrative descriptions of each incident.
    """)

with col2:
    st.image('app/assets/safety_first.jpg', width='stretch')

st.divider()

st.subheader('RAG Chatbot')

if 'question' not in st.session_state:
    st.session_state.question = ''

st.markdown('**Example questions:**')
examples = [
    'What causes hand injuries?',
    'What are common causes of fall injuries?',
    'What industries have the most severe injuries?'
]

cols = st.columns(len(examples))
for col, example in zip(cols, examples):
    with col:
        if st.button(example, width='stretch'):
            st.session_state.question = example

question = st.text_input(
    'Ask a question about workplace injuries:',
    value=st.session_state.question,
    placeholder='e.g. What causes hand injuries?'
)

k = st.selectbox('Number of records to retrieve', options=[3, 5, 7, 10], index=1)
if st.button('Ask', type='primary') and question.strip():
    with st.spinner('Retrieving records and generating answer...'):
        results = retrieve(question, k=k)
        answer = rag_query(question, results)
    
    st.divider()

    ans_col, rec_col = st.columns([2, 1])
    
    with ans_col:
        st.subheader('Answer')
        st.markdown(answer)
    
    with rec_col:
        st.subheader('Retrieved Records')
        for i, r in enumerate(results, 1):
            with st.expander(f"{i}. {r['injury_type']}"):
                st.write(r['text'])

st.divider()
st.markdown('<small>Built by <a href="https://alekivetz.github.io/">Angela Lekivetz</a> · Data sourced from OSHA via Kaggle · Powered by Claude (Anthropic)</small>', unsafe_allow_html=True)